services:
  server-blogs:
    build: ./crates/cringy-blog-blogs
    depends_on:
      postgres-blogs:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres-blogs:5432/cringy-blog
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
  postgres-blogs:
    image: ubuntu/postgres:latest
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cringy-blog
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 5

  server-tasks:
    build: ./crates/cringy-blog-tasks
    depends_on:
      postgres-tasks:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres-tasks:5432/cringy-blog
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
  postgres-tasks:
    image: ubuntu/postgres:latest
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cringy-blog
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 5

  krakend:
    image: devopsfaith/krakend:latest
    depends_on:
      - server-blogs
      - server-tasks
      - jaeger
      - prometheus
      - grafana
      - keycloak
    ports:
      - 8080:8080
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/__health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.40
    ports:
      - 16686:16686 # serve frontend
      # - 14268:14268 # accept jaeger.thrift directly from clients

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  influxdb:
    image: influxdb:1.8.10
    environment:
      - INFLUXDB_DB=krakend
      - INFLUXDB_USER=krakend
      - INFLUXDB_USER_PASSWORD=krakend
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
