services:
  server:
    image: cringy-blog-tasks:latest
    pull_policy: never
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/cringy-blog
  postgres:
    image: ubuntu/postgres:latest
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cringy-blog
